In [1]:
import pandas as pd
import numpy as np
import re

# 1. 데이터 로드

In [2]:
keyword = pd.read_csv('6_visit_jeju_c1_final_cleaned.csv', encoding="utf-8")
df = pd.DataFrame(keyword)
df.head(20)

,contentsid,title,roadaddress,introduction,latitude,longitude,phoneno,region1cd_value,region1cd_label,region2cd_value,region2cd_label,repPhoto_descseo,repPhoto_photoid_photoid,repPhoto_photoid_imgpath,repPhoto_photoid_thumbnailpath,merged_tag
0,CNTS_000000000019003,제주국제예술센터,제주특별자치도 서귀포시 대정읍 서삼중로 117,제주의 문화와 예술이 담긴 곳,33.271830,126.199440,010-4696-8799,region2,서귀포시,22,대정,제주국제예술센터,4131,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['예술', '실내', '미술/박물관', '흐림', '사계절', '실내관광지', '..."
1,CNTS_300000000012728,제주펫스쿨,제주특별자치도 서귀포시 대정읍 칠전로 438,“반려견과 보호자가 함께하는 올바른 반려문화를 만들어요.”\r\n 제주펫스쿨에서는 ...,33.286427,126.223154,0507-1365-4504,region2,서귀포시,22,대정,제주펫스쿨,2019022621770,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['반려견유치원', '반려견호텔', '반려동물', '반려동물동반입장', '혼저옵서개..."
2,CNTS_300000000013522,샤카다이브,제주특별자치도 서귀포시 남원읍 일주동로 8034 (하례리) 1,제주 서귀포시에 위치한 다이빙샵 샤카다이브 입니다,33.325226,126.596193,010-2335-6446,region2,서귀포시,25,남원,샤카다이브,2019022651417,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['해양스포츠', ' 스쿠버다이빙', ' 체험다이빙', ' 야간다이빙', ' 자격증..."
3,CNTS_300000000013707,그림휴가,제주특별자치도 서귀포시 효돈로 114 (신효동) 1층,"미술작가 김미형이 서귀포에 문을 연 미술공간이다. 작품 감상 및 구매, 초상화 주문...",33.263622,126.611108,0507-1426-5071,region2,서귀포시,21,서귀포시내,그림휴가,2019022655924,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['제주', ' 서귀포', ' 갤러리', ' 미술관', ' 작은미술관', ' 그림공..."
4,CNTS_000000000021026,상추자포구,제주특별자치도 제주시 추자면 대서리,상추자도 추자항에 위치한 포구,33.964290,126.292984,--,region3,섬 속의 섬,32,추차도,상추자포구,2019022560665,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['포구', '해변', '문화유적지', '자연경관', '역사유적']"
5,CNTS_300000000013764,하이어스 제주,제주특별자치도 제주시 신성로 82-4 1층,특별한 추억과 실용적인 작품을 남기는 제주 공방,33.495218,126.528154,0507-1416-5919,region1,제주시,11,제주시내,하이어스 제주,2019022656480,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['원데이클래스', ' 공방', ' 체험', ' 이색체험', ' 제주이색코스', '..."
6,CNTS_300000000015837,뎁스원 프리다이빙센터,제주특별자치도 제주시 한림읍 한림로 375,전문적으로 프리다이빙을 배워볼 수 있는 곳,33.396264,126.243239,010-4446-3526,region1,제주시,13,한림,뎁스원 프리다이빙센터,2019022617552,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['맑음', '체험관광', '액티비티', '해변', ' 한림', ' 협재', ' 프..."
7,CNTS_000000000019551,곽지패총,제주특별자치도 제주시 애월읍 곽지리 2043-1,제주 북제주군 애월읍 곽지리에 있는 청동기시대에서 원삼국시대에 걸친 시기의 패총 유적,33.445880,126.307140,064-728-2731,region1,제주시,12,애월,Gwakji Seashell Mound,5490,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['문화유적지', '자연경관', '문화관광', '역사유적']"
8,CONT_000000000500217,발이오름,제주특별자치도 제주시 애월읍 어음리 산 1,바리때 형상을 하고 있는 발이오름,33.395872,126.346288,NaN,region1,제주시,12,애월,Bali Oreum Volcanic Cone,17852,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['오름', '걷기/등산', '자연경관', '도보여행', '도보']"
9,CNTS_000000000021036,용둠범목제계단길,제주특별자치도 제주시 추자면 영흥리,나바론 절벽의 위용을 한 눈에 감상하는 전망대,33.956703,126.296970,--,region3,섬 속의 섬,32,추차도,용둠범목제계단길,10443,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['걷기/등산', '도보여행', '도보']"
10,CNTS_000000000022858,오림반,제주특별자치도 서귀포시 남원읍 신례리,4․3 초기 무장대들이 훈련을 받았던 곳으로 추정되는 곳,33.360670,126.597190,--,region2,서귀포시,25,남원,오림반,16749,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['4.3', '문화유적지', '문화관광', '제주4.3', '역사유적', '어트랙션']"
11,CONT_000000000500597,족은사슴이오름,제주특별자치도 서귀포시 표선면 녹산로 536,자연이 살아숨쉬는 곳,33.398807,126.706334,NaN,region2,서귀포시,26,표선,Jokeunsaseumi Oreum Volcanic Cone,19873,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['부모', '커플', '혼자', '친구', '아이', '오름', '자연경관', '..."
12,CNTS_000000000019458,옹포천,제주특별자치도 제주시 한림읍 한림로 563,서부지역의 상수원,33.407660,126.257420,--,region1,제주시,13,한림,옹포천,5329,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['휴식/힐링', '맑음', '자연경관', '공용주차장', '화장실']"
13,CNTS_000000000020247,협자연대,제주특별자치도 서귀포시 성산읍 고성리 57-1,성산읍 고성리에 위치한 제주특별자치도 기념물 제23-2호 협자연대,33.426456,126.932304,064-760-2505,region2,서귀포시,17,성산,Hyeopja Signaling Site,8039,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['문화유적지', '문화관광', '역사유적', '어트랙션']"
14,CNTS_000000000021510,신산환해장성,제주특별자치도 서귀포시 성산읍 신산리,자연으로 빚은 성벽,33.384760,126.866520,--,region2,서귀포시,17,성산,신산환해장성,11443,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['문화유적지', '흐림', '자연경관', '문화관광', '역사유적', '아주 어려움']"
15,CONT_000000000500013,가문이오름(감은이오름),제주특별자치도 서귀포시 표선면 남조로 1487-73,숲이 우거져 검게 보인다고 해서 붙여진 가문이오름,33.370809,126.693520,064-760-2913,region2,서귀포시,26,표선,Gamuni Oreum Volcanic Cone (Gameuni Oreum Volc...,16965,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['커플', '혼자', '친구', '맑음', '오름', '가을', '자연경관', '..."
16,CNTS_000000000022032,라신동,제주특별자치도 제주시 한림읍 귀덕리,· 올레15코스,33.431778,126.290634,--,region1,제주시,13,한림,라신동,12478,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['문화유적지', '문화관광', '역사유적', '어트랙션']"
17,CNTS_000000000019084,섬생이,제주특별자치도 제주시 추자면 신양리 산 87,풍경이 아름다운 추자도 남쪽 무인도,33.939816,126.311540,--,region3,섬 속의 섬,32,추차도,Seomsaengi,4268,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['휴식/힐링', '자연경관']"
18,CNTS_300000000015883,제주해양레저타운,제주특별자치도 제주시 서해안로 58,이호테우 바다에서 즐기는 짜릿한 레저,33.502152,126.456411,0507-1347-7064,region1,제주시,11,제주시내,제주해양레저타운,2019022617935,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['제주시내', ' 이호테우', ' 수상레저', ' 제트스키', ' 제트보트', '..."
19,CNTS_000000000022007,풋감마을 소길리 농어촌체험마을,제주시 애월읍 소길1길 15,옛 '올레'길이 그대로 살아 숨쉬는 마을,33.440056,126.380005,064-799-8778,region1,제주시,12,애월,풋감마을 소길리 농어촌체험마을,12368,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,"['체험관광', '친구', '커플', '흐림', '사계절', '체험', '도보여행'..."

# 2. 전처리

### 1) 신규 칼럼 추가

* 제주 관광 권역별 신규 칼럼 추가 'by_region_label'         
    * 제주시내 / 서귀포시내 / 제주시_동부/ 제주시_서부 / 제주시_기타 / 서귀포시_동부 / 서귀포시_서부          
    * 총 7개 관광 권역별로 표기시 지도 표시 용이

In [3]:
df['region2cd_label'].value_counts()

region2cd_label
제주시내     261
서귀포시내    178
구좌       113
애월       109
조천       105
안덕        99
한림        72
성산        70
남원        66
대정        60
한경        58
표선        52
중문        39
추차도       26
우도        22
마라도        6
비양도        2
가파도        2
차귀도        1
Name: count, dtype: int64

In [4]:
# 추차도 (오타) -> 추자도로 수정

In [5]:
df['region2cd_label'] = df['region2cd_label'].str.replace("추차도", "추자도", regex=False)

In [6]:
region_map = {
    "제주시내": "제주시내",
    "서귀포시내": "서귀포시내",
    "구좌": "제주시_동부",
    "조천": "제주시_동부",
    "우도": "제주시_동부",
    "애월": "제주시_서부",
    "한림": "제주시_서부",
    "한경": "제주시_서부",
    "비양도": "제주시_서부",
    "차귀도": "제주시_서부",
    "성산": "서귀포시_동부",
    "남원": "서귀포시_동부",
    "표선": "서귀포시_동부",
    "추자도": "제주시_기타",
    "안덕": "서귀포시_서부",
    "대정": "서귀포시_서부",
    "중문": "서귀포시_서부",
    "마라도": "서귀포시_서부",
    "가파도": "서귀포시_서부",
}

In [7]:
# 추자도는 제주도 본섬에서 북쪽으로 45km 떨어진 섬임. 관광 기준으로 별개의 지역으로 판단. '제주시_기타'로 별개로 분류

In [8]:
df['by_region_label'] = df['region2cd_label'].map(region_map)

In [9]:
df[['region2cd_label', 'by_region_label']]

     region2cd_label by_region_label
0                 대정         서귀포시_서부
1                 대정         서귀포시_서부
2                 남원         서귀포시_동부
3              서귀포시내           서귀포시내
4                추자도          제주시_기타
...              ...             ...
1336              표선         서귀포시_동부
1337              남원         서귀포시_동부
1338              표선         서귀포시_동부
1339            제주시내            제주시내
1340              구좌          제주시_동부

[1341 rows x 2 columns]

### 2) 텍스트 전처리

(1-1) **불필요한 문자 제거**                   
    (예: `#`, `\t\t\t\t\t\t\t\t\t`, 빈 문자열('') 등)

(1-2) **[] 대괄호 제거**

(1-3) **공백 대체 후 단어 분리**               
    * 단어 사이 `/`, `.`, `+`를 공백으로 변환 후  구분자(,)로 분리                 
    (예: `휴식/힐링` → '휴식 힐링' `휴식`, `힐링`)                   
    (예: `비.눈` → '비 눈' ->  `비`, `눈`)                  
    (예: `실내+실외` → '실내 실외' -> `실내`, `실외`)              
    ※ 단, `4.3사건`과 같은 고유명사는 변환하지 않도록 예외 처리

In [10]:
df['merged_tag_cleaned'] = (
    df['merged_tag'].astype(str)
      .str.replace(r"[\\t]", "", regex=True)      # '\t' 반복 → 삭제
      .str.replace(r"[#\[\]'\"]", "", regex=True)  # '#', '[]', 따옴표 삭제
      .str.replace(r"[\/+]", ",", regex=True)      # '/', '+' → ,로 변경
      .str.replace(r"(?<!\d)\.(?!\d)", ",", regex=True)  # 숫자가 아닌 점 → ,로 변경
      .str.replace(r"['']", '', regex=True)        # 빈값 → 삭제
      .str.strip()                      # 양쪽 공백 제거
)

* 전처리 결과 확인

In [11]:
df[['merged_tag','merged_tag_cleaned']].loc[253:254] # '[]'제거, +'제거,  실내+실외  → 실내,실외

,merged_tag,merged_tag_cleaned
253,"['서귀포', ' 안덕면', ' 동광리', ' 승마', ' 포니', ' 이색체험',...","서귀포, 안덕면, 동광리, 승마, 포니, 이색체험, 실내,실외, 중, 1시..."
254,"['커플', '혼자', '친구', '휴식/힐링', '체험관광', '사계절', '청년...","커플, 혼자, 친구, 휴식,힐링, 체험관광, 사계절, 청년, 공용주차장, 화장실, ..."

In [12]:
df[['merged_tag','merged_tag_cleaned']].loc[434:435] #  '#'제거, 경관/포토 → 경관,포토

,merged_tag,merged_tag_cleaned
434,"['#예술 #경관/포토', '문화관광', '포토스팟']","예술 경관,포토, 문화관광, 포토스팟"
435,"['구좌읍', ' 월정리', ' 서핑', ' 이색체험', '실외', '중', '3시...","구좌읍, 월정리, 서핑, 이색체험, 실외, 중, 3시간 이상"

In [13]:
df[['merged_tag','merged_tag_cleaned']].loc[608:609] # '\t' 제거, 케이팝\t\t\t\t\t\t\t\t\t → 케이팝

,merged_tag,merged_tag_cleaned
608,"['조천', ' 뮤직비디오촬영지', ' 케이팝\t\t\t\t\t\t\t\t\t']","조천, 뮤직비디오촬영지, 케이팝"
609,"['포토스팟', ' 사진명소', ' 동백꽃', ' 감귤따기', ' 귤따기체험', '...","포토스팟, 사진명소, 동백꽃, 감귤따기, 귤따기체험, 정원카페, 공용주차장..."

In [14]:
df[['merged_tag','merged_tag_cleaned']].loc[1153:1154] # '4.3'같은 고유명사는 .삭제 제외, #비.눈 → 비,눈

,merged_tag,merged_tag_cleaned
1153,"['4.3', '실내', '미술/박물관', '부모', '비.눈', '봄', '자연경...","4.3, 실내, 미술,박물관, 부모, 비,눈, 봄, 자연경관, 문화관광, 제주4.3..."
1154,"['등대', '경관/포토', '맑음', '포토스팟', '어트랙션', '수국', '공...","등대, 경관,포토, 맑음, 포토스팟, 어트랙션, 수국, 공용주차장, 화장실"

* (1-3)까지 전처리 상태 확인 : 전처리가 안된 3개 행은 replace로 값 교체

In [15]:
# 434행 
df.loc[434, 'merged_tag_cleaned'] = df.loc[434, 'merged_tag_cleaned'].replace('예술  경관', '예술, 경관')
df.loc[434, 'merged_tag_cleaned']

'예술, 경관,포토, 문화관광, 포토스팟'

In [16]:
# 1144행
df.loc[1144, 'merged_tag_cleaned'] = df.loc[1144,'merged_tag_cleaned'].replace(', 제주도 ', '제주도')
df.loc[1144, 'merged_tag_cleaned']

'제주도, 제주여행 , 제주관광 , 제주관광지 , 제주명소 , 제주힐링 , 제주야자수 , 숲캉스, 공용주차장, 화장실, 실외'

In [17]:
#1166행
df.loc[1166, 'merged_tag_cleaned'] = df.loc[1166,'merged_tag_cleaned'].replace('의료관광 병원 웰니스  헬스케어', '의료관광, 병원, 웰니스, 헬스케어')
df.loc[1166, 'merged_tag_cleaned']

'의료관광, 병원, 웰니스, 헬스케어, 의료관광'

* ,, 콤마 이중으로 들어간 부분 replace로 값 교체

In [18]:
df['merged_tag_cleaned'] = df['merged_tag_cleaned'].str.replace(', ,', ',', regex=False)

*  중복값 삭제 (ex. 힐링, , 힐링 / 의료관광, 의료관광 )

In [19]:
df['merged_tag_cleaned'] = df['merged_tag_cleaned'].apply(
    lambda x: ', '.join(dict.fromkeys([t.strip() for t in x.split(',') if t.strip()]))
)

In [20]:
df.loc[575, 'merged_tag_cleaned']

'스파, 힐링, 숙소, 리조트, 어트랙션'

In [21]:
df.loc[1166, 'merged_tag_cleaned']

'의료관광, 병원, 웰니스, 헬스케어'

In [22]:
# df.to_csv('8_visit_jeju_c1_tag_cleaned.csv',index=False, encoding='utf-8') #-- 중간 참고용

(1-4) **분석 목적과 관련성 낮은 태그 제거**                  
* 의미 없음                   
    (예: `상`, `중`, `하`, `쉬움`, `어려움`, `아주 어려움`, `1시간 미만`, `1~2시간`, `2~3시간`, `3시간 이상`, `단독접근가능`)

- 편의시설·결제 방법 태그                 
    (예: `공용주차장`, `카드결제`, `현금결제', '지역화폐(카드형)`, `지역화폐(지류평,카드형)`, `문화누리카드` `화장실`, `무료 WIFI`, `흡연구역`, `편의점`, `음료대`, `유도 및 안내시설`, `경보 및 피난시설`)

※ 편의시설 정보는 프론트 엔드 화면 구현에서 필요.                     
   따라서 원본파일 및 데이터 분석을 위해 해당 태그 삭제한 버전 모두 저장

In [23]:
# 단어 내 공백 제거

In [24]:
df['merged_tag_cleaned'] = df['merged_tag_cleaned'].str.replace(r'\s+', '', regex=True)
df[['merged_tag_cleaned']].head(6)

                                  merged_tag_cleaned
0         예술,실내,미술,박물관,흐림,사계절,실내관광지,어트랙션,공용주차장,아주어려움
1  반려견유치원,반려견호텔,반려동물,반려동물동반입장,혼저옵서개,반려동물동반_기타체험,공...
2  해양스포츠,스쿠버다이빙,체험다이빙,야간다이빙,자격증코스,펀다이빙,공용주차장,현금결제...
3  제주,서귀포,갤러리,미술관,작은미술관,그림공방,작품감상,작품구매,초상화,주문제작,소...
4                              포구,해변,문화유적지,자연경관,역사유적
5                   원데이클래스,공방,체험,이색체험,제주이색코스,하,1~2시간

In [25]:
# df.to_csv('8_visit_jeju_c1_tag_cleaned.csv',index=False, encoding='utf-8') #-- 중간 참고용

* 의미 없는 키워드 삭제

상,중,하,쉬움,어려움,아주어려움,1시간미만,1~2시간,2~3시간,3시간이상, 단독접근가능

In [26]:
remove_words = ['상','중','하','쉬움','어려움','아주어려움','1시간미만','1~2시간','2~3시간','3시간이상', '단독접근가능']

pattern = r'\b(?:' + '|'.join(remove_words) + r')\b'
df['merged_tag_cleaned'] = df['merged_tag_cleaned'].str.replace(pattern, '', regex=True)

* (1-4) 의미없는 키워드 삭제 후 전처리 상태 확인 : 전처리가 안된 4개 행은 replace로 값 교체

In [27]:
#245행
df.loc[245, 'merged_tag_cleaned'] = df.loc[245, 'merged_tag_cleaned'].replace('제주요가요가힐링명상빈야사요가제주요가원제주요가원데이', '제주요가,요가,힐링,명상,빈야사요가,제주요가원,제주요가원데이')
df.loc[245, 'merged_tag_cleaned']

'제주요가,요가,힐링,명상,빈야사요가,제주요가원,제주요가원데이'

In [28]:
#1213행
df.loc[1213, 'merged_tag_cleaned'] = df.loc[1213, 'merged_tag_cleaned'].replace('혼자,필라테스,메디컬요가,요가,어트랙션,공용주차장,현금결제,카드결제,화장실,체험,기구필라테스,메디컬요가', '혼자,필라테스,메디컬요가,요가,어트랙션,공용주차장,현금결제,카드결제,화장실,체험,기구필라테스')
df.loc[1213, 'merged_tag_cleaned']

'혼자,필라테스,메디컬요가,요가,어트랙션,공용주차장,현금결제,카드결제,화장실,체험,기구필라테스,'

In [29]:
# 1129행 () →  여는 괄호 _ 처리, 닫는 괄호 삭제 ex. 중국어(사전문의) → 중국어_사전문의
df.loc[1129, 'merged_tag_cleaned']

'제주동쪽가볼만한곳,서귀포가볼만한곳,제주여행,제주수국축제,제주관광지도,7월제주,제주관광지,제주야경명소,제주야경,반려동물,반려동물동반입장,혼저옵서개,반려동물동반_관광지,공용주차장,현금결제,카드결제,화장실,무료WIFI,편의점,음료대,유도및안내시설,경보및피난시설,영어,중국어,일본어,중국어(사전문의),단차없음,장애인화장실,장애인전용주차장,수동휠체어대여가능,,실내,실외,,포토스팟,'

In [30]:
# 1115행 ()에 오타 존재 및 값 2개 있음.  지역화폐(지류평,카드형) → 지역화폐_지류형, 지역화폐_카드형으로 수정
df.loc[1115, 'merged_tag_cleaned'] = df.loc[1115, 'merged_tag_cleaned'].replace('지역화폐(지류평,카드형)', '지역화폐_지류형,지역화폐_카드형')
df.loc[1115, 'merged_tag_cleaned']

'제주여행,제주도놀거리,제주서쪽,동물농장,독수리,올빼미,백조,앵무새,먹이주기,공용주차장,화장실,카드결제,현금결제,지역화폐_지류형,지역화폐_카드형,문화누리카드'

In [31]:
df['merged_tag_cleaned'] = df['merged_tag_cleaned'].str.replace(r'\((.*?)\)', r'_\1', regex=True)

* 전처리 결과 확인

In [32]:
df.loc[1129, 'merged_tag_cleaned']

'제주동쪽가볼만한곳,서귀포가볼만한곳,제주여행,제주수국축제,제주관광지도,7월제주,제주관광지,제주야경명소,제주야경,반려동물,반려동물동반입장,혼저옵서개,반려동물동반_관광지,공용주차장,현금결제,카드결제,화장실,무료WIFI,편의점,음료대,유도및안내시설,경보및피난시설,영어,중국어,일본어,중국어_사전문의,단차없음,장애인화장실,장애인전용주차장,수동휠체어대여가능,,실내,실외,,포토스팟,'

In [33]:
df.loc[1115, 'merged_tag_cleaned']

'제주여행,제주도놀거리,제주서쪽,동물농장,독수리,올빼미,백조,앵무새,먹이주기,공용주차장,화장실,카드결제,현금결제,지역화폐_지류형,지역화폐_카드형,문화누리카드'

In [34]:
# df.to_csv('8_visit_jeju_c1_tag_cleaned.csv',index=False, encoding='utf-8') #-- 중간 참고용

* 콤마 여러개  → ,로 변경
* 맨 마지막 단어 끝에 있는 콤마 → 삭제

In [35]:
df['merged_tag_cleaned'] = (
    df['merged_tag_cleaned']
      .str.replace(r'\s*,\s*', ',', regex=True)  # 콤마 주변 공백 제거
      .str.replace(r',+', ',', regex=True)       # 콤마 중복 제거
      .str.replace(r',\s*$', '', regex=True)     # 끝 콤마 제거
)

In [36]:
# df.to_csv('8_visit_jeju_c1_tag_cleaned.csv',index=False, encoding='utf-8') #-- <저장완료>

# 최종 CSV 파일 구분

### 1. 프론트백엔드용 CSV파일

[파일 설명]
- 편의시설·결제 방법 태그 포함
- 관광권역별 칼럼 추가 (by_region_label)

In [37]:
df.columns

Index(['contentsid', 'title', 'roadaddress', 'introduction', 'latitude',
       'longitude', 'phoneno', 'region1cd_value', 'region1cd_label',
       'region2cd_value', 'region2cd_label', 'repPhoto_descseo',
       'repPhoto_photoid_photoid', 'repPhoto_photoid_imgpath',
       'repPhoto_photoid_thumbnailpath', 'merged_tag', 'by_region_label',
       'merged_tag_cleaned'],
      dtype='object')

In [38]:
df_end = df[['contentsid', 'title', 'roadaddress', 'introduction', 'latitude',
       'longitude', 'phoneno', 'region1cd_value', 'region1cd_label',
       'region2cd_value', 'region2cd_label', 'repPhoto_descseo',
       'repPhoto_photoid_photoid', 'repPhoto_photoid_imgpath',
       'repPhoto_photoid_thumbnailpath', 'by_region_label',
       'merged_tag_cleaned']]

* 최종 전처리 결과 확인

In [39]:
df_end.head(1)

,contentsid,title,roadaddress,introduction,latitude,longitude,phoneno,region1cd_value,region1cd_label,region2cd_value,region2cd_label,repPhoto_descseo,repPhoto_photoid_photoid,repPhoto_photoid_imgpath,repPhoto_photoid_thumbnailpath,by_region_label,merged_tag_cleaned
0,CNTS_000000000019003,제주국제예술센터,제주특별자치도 서귀포시 대정읍 서삼중로 117,제주의 문화와 예술이 담긴 곳,33.27183,126.19944,010-4696-8799,region2,서귀포시,22,대정,제주국제예술센터,4131,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,서귀포시_서부,"예술,실내,미술,박물관,흐림,사계절,실내관광지,어트랙션,공용주차장"

* csv 파일 저장

In [40]:
# df_end.to_csv('9_visit_jeju_c1_tag_final_cleaned.csv',index=False, encoding='utf-8') #-- <저장완료>

### 2. 데이터분석용 CSV파일

- 편의시설·결제 방법 태그 삭제             
    (예: `공용주차장`, `카드결제`, `현금결제', '지역화폐(카드형)`, `지역화폐(지류평,카드형)`, `문화누리카드`, `화장실`, `무료 WIFI`, `흡연구역`, `편의점`, `음료대`, `유도 및 안내시설`, `경보 및 피난시설`)

In [41]:
remove_tags = [
    '공용주차장', '카드결제', '현금결제', '지역화폐_카드형', 
    '지역화폐_지류형', '문화누리카드', '화장실', 
    '무료WIFI', '흡연구역', '편의점', '음료대', 
    '유도및안내시설', '경보및피난시설'
]

pattern = r'\b(?:' + '|'.join(remove_tags) + r')\b'
df['merged_tag_cleaned_for_da'] = df['merged_tag_cleaned'].str.replace(pattern, '', regex=True)

In [42]:
df['merged_tag_cleaned_for_da'] = (
    df['merged_tag_cleaned_for_da']
      .str.replace(r'\s*,\s*', ',', regex=True)  # 콤마 주변 공백 제거
      .str.replace(r',+', ',', regex=True)       # 콤마 중복 제거
      .str.replace(r',\s*$', '', regex=True)     # 끝 콤마 제거
)

In [43]:
df_for_da =  df[['contentsid', 'title', 'roadaddress', 'introduction', 'latitude',
       'longitude', 'phoneno', 'region1cd_value', 'region1cd_label',
       'region2cd_value', 'region2cd_label', 'repPhoto_descseo',
       'repPhoto_photoid_photoid', 'repPhoto_photoid_imgpath',
       'repPhoto_photoid_thumbnailpath', 'by_region_label',
       'merged_tag_cleaned_for_da']]

* 최종 전처리 결과 확인

In [44]:
df_for_da.head(1)

,contentsid,title,roadaddress,introduction,latitude,longitude,phoneno,region1cd_value,region1cd_label,region2cd_value,region2cd_label,repPhoto_descseo,repPhoto_photoid_photoid,repPhoto_photoid_imgpath,repPhoto_photoid_thumbnailpath,by_region_label,merged_tag_cleaned_for_da
0,CNTS_000000000019003,제주국제예술센터,제주특별자치도 서귀포시 대정읍 서삼중로 117,제주의 문화와 예술이 담긴 곳,33.27183,126.19944,010-4696-8799,region2,서귀포시,22,대정,제주국제예술센터,4131,https://api.cdn.visitjeju.net/photomng/imgpath...,https://api.cdn.visitjeju.net/photomng/thumbna...,서귀포시_서부,"예술,실내,미술,박물관,흐림,사계절,실내관광지,어트랙션"

* csv 파일 저장

In [45]:
# df_for_da.to_csv('10_visit_jeju_c1_tag_final_cleaned_for_da.csv',index=False, encoding='utf-8') #-- <저장완료>